### ISSUE TITLE
Catch Fiware-ServicePath multi-item situations

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#1121]
Current behaviour: when Cygnus receives a notification with many comma-separated items in the Fiware-ServicePath header (typically corresponding to initial notifications from Orion) it print in the logs:

'fiware-servicePath' header length greater than 50

It would be great to distinghish this situation from the one corresponding to just one element in the header with actual size greater than 50.

Thus, the check could be implemented in two step:

1. Check that the Fiware-ServicePath has several items. In this case, the message to print will be in the following style: "notification has several SP items, probably this is csub initial notification and will be ignored".
2. If th following check is passed, Fiware-ServicePath is mono-item. Now check for length and print the usual "header length greater than X" message in this case.

**Comment by frbattid** [comment]
Multivalued FIWARE service paths issue was already [described](https://github.com/telefonicaid/fiware-cygnus/issues/923) and [fixed]( https://github.com/telefonicaid/fiware-cygnus/pull/937) from the processing point of view. The problem is at the reception of the notification, whilde deciding if it is accepted or droped. More specifically, the problem is at the header length check: it does not check value by value, but considers the notified string as a single value. Thus, the following scenarios may arise:

* A single valued header with lenght under 50 characters:
    * The notification is accepted, and it is successfully processed.
    * For instance, `/basuras`.
* A single valued header with length over 50 characters:
    * The notification is not accepted, as expected, and nothing has to be processed.
    * For instance, `/looooooooooooooooooooooooooooooooooooooooooooooooooooooong`.
* A multi-valued header with total length under 50 characters:
    * The notification is accepted, and it is successfully processed.
    * For instance, `/basuras,/jardines,/fuentes`.
* A multi-valued header with total length over 50 characters:
    * The notification is not accepted, which is **wrong**.
    * For instance, `/basuras,/jardines,/fuentes,/trafico,/bicicletas,/camaras,/parques,/museos`.

The last case is fixed if the length check is done value by value.

**Comment by frbattid** [comment]
This is going to be fixed when implementing the issue https://github.com/telefonicaid/fiware-cygnus/issues/407
