### ISSUE TITLE
[cygnus][api] DELETE subscription error

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1147]
As reported by a FIWARE user:

The test was done using the Cygnus version 1.2.0 on a Centos S.O.

The subscriptions's DELETE doesn't work due to an error on the input parameters.
It seems that the two parameters sent into the requests are not processed togheter. Only one of these is analyzed. The second one always not.
Note that I performed a DELETE operation directly on the ORION server using CURL and also a REST request. In both cases it works and the subscription was deleted correctly.

Here a recap of all 4 types of tests done.

    First test sending the ngsi_version as first param
    [centos@cygnus ~]$ curl --include --request DELETE http://localhost:8081/v1/subscriptions?ngsi_version=1&subscription_id=57c93ec8c1ff5ffad218f7cd
    [1] 31461
    [centos@cygnus ~]$ HTTP/1.1 400 Bad Request
    Content-Type: application/json; charset=utf-8
    Content-Length: 99
    Server: Jetty(6.1.26)

{"success":"false","error":"Parse error, wrong parameter (subscription_id). Check it for errors."}

[1]+ Done curl --include --request DELETE http://localhost:8081/v1/subscriptions?ngsi_version=1
[centos@cygnus ~]$

    Second test sending the subscription_id as first param
    [centos@cygnus ~]$ curl --include --request DELETE http://localhost:8081/v1/subscriptions?subscription_id=57c93ec8c1ff5ffad218f7cd&ngsi_version=1
    [1] 31575
    [centos@cygnus ~]$ HTTP/1.1 400 Bad Request
    Content-Type: application/json; charset=utf-8
    Content-Length: 96
    Server: Jetty(6.1.26)

{"success":"false","error":"Parse error, wrong parameter (ngsi_version). Check it for errors."}

[1]+ Done curl --include --request DELETE http://localhost:8081/v1/subscriptions?subscription_id=57c93ec8c1ff5ffad218f7cd

In both of tests it seems that only the first parameter is processed.

    Third test. I passed the address into the single quote '. The error is different. Is missing an end point
    [centos@cygnus ~]$ curl --include --request DELETE 'http://localhost:8081/v1/subscriptions?ngsi_version=1&subscription_id=57c93ec8c1ff5ffad218f7cd'
    HTTP/1.1 400 Bad Request
    Content-Type: application/json; charset=utf-8
    fiware-correlator: 178d26c1-7524-40b2-853d-fc16976f13f1
    Content-Length: 47
    Server: Jetty(6.1.26)

{"success":"false","error":"Missing endpoint"}

[centos@cygnus ~]$

    Fourth test. I passed a / slash as and endpoint. The error is that the operation is not implemented.
    [centos@cygnus ~]$ curl --include --request DELETE 'http://localhost:8081/v1/subscriptions/?ngsi_version=1&subscription_id=57c93ec8c1ff5ffad218f7cd'
    HTTP/1.1 501 Not Implemented
    Content-Type: text/html; charset=utf-8
    Content-Length: 42
    Server: Jetty(6.1.26)

DELETE /v1/subscriptions/ Not implemented
[centos@cygnus ~]$

**Comment by pcoello25** [comment]
Result from tests:
```
[POSTING A SUBSCRIPTION --> SUBSCRIPTION_ID = 57d2814e5a504f61435415cc]
$ curl -X POST "http://localhost:8081/v1/subscriptions?ngsi_version=1" -H "Content-Type", "application/json; charset=utf-8" -d '{"subscription":{"entities": [{"type": "Room","isPattern": "false","id": "Room1"}],"attributes": [],"reference": "http://localhost:5050","duration": "P1M","notifyConditions": [{"type": "ONCHANGE","condValues": []}],"throttling": "PT5S"},"endpoint":{"host":"orion.lab.fiware.org", "port":"1026", "ssl":"false", "xauthtoken":"YdoKRrPKfS2Bfy4RT4lacAgGY3rTJc"}}'
{"success":"true","result" : {{"subscribeResponse":{"duration":"P1M","throttling":"PT5S","subscriptionId":"57d2814e5a504f61435415cc"}}}
```

Once done the subscription it's time to check the reported bugs. Summarizing:
* First test is about the order of the parameters. 
* Second test is about the order too.
* Third test is about a missing endpoint
* Fourth tests is about a not implemented method.

Let's see an example and explain what's the problem. I use `curl` for the requests:
```
curl -X DELETE "http://localhost:8081/v1/subscriptions?ngsi_version=1&subscription_id=57d2814e5a504f61435415cc" -d '{"host":"orion.lab.fiware.org", "port":"1026", "ssl":"false", "xauthtoken":"YdoKRrPKfS2Bfy4RT4lacAgGY3rTJc"}'
{"success":"true","result" : {" Subscription deleted "}}
```
In this case I flipped the order of the parameters, putting first `ngsi_version` and then `subscription_id`. As you can see there aren't problem with it. 

In the third test, as the logs say, there aren't `endpoint`. It's true that checking the documentation the example is incomplete (forgot to add the endpoint at the end of the request. I'll fix right now). You need to add the endpoint due to Orion need to know that you are sending an unsubscribecontext. If you send the request like that you will receive a bad request.

In the fourth test, as the log say, there aren't a method `DELETE /v1/subscriptions/'  implemented. In your request you have an extra slash at the end. For that reason the method is invalid. If you delete that slash and add the endpoint as you see in the example you won't have problems with the request.

Thanks for the feedback, it's useful for us and we can fix mistakes that we don't realize :)

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1155
