### ISSUE TITLE
Proper processing of mongo codes in MongoBackendImplementation

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#1756]
Current Mongo backend implementation process responses from the server in a weak way, based in string processing. In particular in two places:

https://github.com/telefonicaid/fiware-cygnus/blob/88386f198d65eb18554190b4af455efc4f53e44e/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mongo/MongoBackendImpl.java#L106-L115

https://github.com/telefonicaid/fiware-cygnus/blob/88386f198d65eb18554190b4af455efc4f53e44e/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mongo/MongoBackendImpl.java#L171-L177

This part: `e.getMessage().contains("\"code\" : 48")` will break if for instance the message responsed by the server changes from `"code" : 48` to `"code":48` (without whitespaces).

The check should be done based on the JSON nature of the data. E.g (pseudocode):

```
e.getMessage().toJson().get("code") == 48
```

**Comment by IvanHdzC** [comment]
There is not native way to convert a Java exception into a Json String. Actually it would be necessary to define the conversion (Java Exception to Json) laytout since it is not standarized.

There are some definitions of this conversion like [Oasis error response ](http://docs.oasis-open.org/odata/odata-json-format/v4.0/errata02/os/odata-json-format-v4.0-errata02-os-complete.html#_Toc403940655). But I'm not sure if it will worth it. 

Probably is better to validate it through a regular expression. What do you thing @fgalan?

**Comment by fgalan** [comment]
Maybe the mongo driver provided some normalized way of accessing to error codes? Maybe it worths the time to have a look

Of course regex processing would be stronger than current plain text matching, but if a proper mechanism is provided by the driver, I'd suggest to use it. Maybe there are examples in the driver documentation on how to do it.

**Comment by IvanHdzC** [comment]
You are right, sorry about that. I didn't really thought it...

**Comment by fgalan** [comment]
Fixed by PR #1760
