### ISSUE TITLE
Cygnus update mode

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1806]
Current sinks implementations allow to insert new entries in a database/file/datastore. It would be desirable to have a special mode in Cygnus that allows to update entries instead of creating new ones.

For instance, SQL sinks, would make an INSERT operation if the record doesn't exist and would make an UPDATE operation if the record exists. The key would be the entity id.

It is thought for scenarios where context Broker has entities which are almost static, but it is interesting to have a table with the last data received without the need to make a "lastdata view" in the database. These tables would have the same number of records as entities in the CB.

This mode would be configured in the sink configuration.

**Comment by fgalan** [comment]
> This mode would be configured in the sink configuration.

Orion allows to specify in the notification if the triggering cause was an update or an append (`actionType` builtin metadata, either `update` or `append`). Cygnus could pay attention to that in order to choose if it INSERT (for append) or UPDATE (for update), instead of (or in addition to) a fixed sink configuration.

However, probably this is not the way we want it works (as many client could "baduse" append for updating context information) but I mention it anyway in the case you weren't aware of this feature in Orion.

**Comment by manucarrace** [comment]
There are several options for the use case we wnt to implement:

1. New cygnus source + additional sink for updates + CB notification for the "static" entities
2. CB custom notification with a specific header + additional sink multiplexed by header
3. A flag in name_mapping "update":true added to the event + a single sink being able to decide whether to insert or update.

Options 1 and 2.

**Comment by AlvaroVega** [comment]
Extend current sink implementation to make:
- insert (like currently does)
- upsert (insert & update) in "_lastdata" table if configured (i.e. a new sink configuration Boolean flag  name  "lastdata"
     PostgreSQL https://www.postgresqltutorial.com/postgresql-upsert/

**Comment by fgalan** [comment]
>    * upsert (?insert & update) in "_lastdata" table if configured (i.e. a new sink configuration Boolean flag  name  "lastdata"
>       PostgreSQL https://www.postgresqltutorial.com/postgresql-upsert/

Instead of a boolean flag lastdata and a hardwired suffix "_lastdata" maybe is more flexible a parameter with the suffix itself.

My two cents... :)

**Comment by IvanHdzC** [comment]
Since the table "_lastdata" will be created as a new one, there shouldn't be a problem with creating a column as 'unique' right?

[The documentation says that in order to use `ON CONFLICT` there must be a 'unique' column in order to successfully use it. ](https://www.postgresql.org/docs/9.5/sql-insert.html#SQL-ON-CONFLICT)

**Comment by IvanHdzC** [comment]
For mySQL is possible to execute an [upsert](https://chartio.com/resources/tutorials/how-to-insert-if-row-does-not-exist-upsert-in-mysql/#using-insert--on-duplicate-key-update) with:

`INSERT ... ON DUPLICATE KEY UPDATE`

But, as in Postgresql it needs a [unique](https://www.mysqltutorial.org/mysql-unique/) key.

**Comment by fgalan** [comment]
Once PR #1934 has been merged, should this issue be closed?

**Comment by fgalan** [comment]
Additional PR #1936

**Comment by fgalan** [comment]
Should this issue be closed?

**Comment by AlvaroVega** [comment]
mysql implementation is expected be done soon.

**Comment by fgalan** [comment]
I undesrtand that now all the SQL-based sinks are covered, so this issue can be closed.

**Comment by fgalan** [comment]
I understand that now all the SQL-based sinks are covered, so this issue can be closed.
