### ISSUE TITLE
change log level still shows logs in previous levels

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1827]
There are some problems changing loglevel using API.
Steps:
curl -X PUT "http://localhost:8081/admin/log?level=DEBUG"
curl -X PUT "http://localhost:8081/admin/log?level=WARN"
and stills appears traces in INFO

Api for change log level was introduced by:
https://github.com/telefonicaid/fiware-cygnus/issues/807
and
https://github.com/telefonicaid/fiware-cygnus/pull/1114

**Comment by smartcitydevops** [comment]
We have detected a similar problem. We have several instances of cygnus. All of them are writing logs in INFO level, as defined in their "properties files" 

We launched in all of them:

curl -X PUT http://127.0.0.1:XXXX/admin/log?level=WARN

With this response

{"success":"log4j logging level updated to WARN" }

But their logs showed no change , because INFO logs are still written in them

Besides

sh-4.4$ curl -X GET http://127.0.0.1:5111/admin/log
{"level":"WARN"}

with INFO logs written in the log file, despite this message. Please check

**Comment by AlvaroVega** [comment]
Just to confirm, @smartcitydevops did you tried with latest version 2.18.0 ?

**Comment by smartcitydevops** [comment]
We have observed this issue with 2.17.0 , deployed in the production environment last May the 11th

**Comment by AlvaroVega** [comment]
I'm already checked with 2.18.0 version and change log level works. Maybe you are putting several cygnus instance logs in the same place at the same time and you observed that others cygnus are reporting in other log level.
Could you do the following test:
- set to debug level
- send an even to cygnus
- set to warn level
- send an even to cygnus
and provide me all reported logs?

**Comment by AlvaroVega** [comment]
> At this point, there were continous DEBUG logs

Show me thtat logs, please.

**Comment by AlvaroVega** [comment]
put log level is just doing getRootLogger and set new level: 

https://github.com/telefonicaid/fiware-cygnus/blob/96d41f62b04ea332c229d7e7e0a3d8c94f409f57/cygnus-common/src/main/java/com/telefonica/iot/cygnus/management/LogHandlers.java#L1038-L1056

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/2170

Once the PR has been closed, should this issue be closed?
