### ISSUE TITLE
[cygnus-ngsi][all sinks] Do per-sink active checkings of element name sizes

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-cygnus#407]
Ex: 
```
time=2015-05-18T11:45:33.121CEST | lvl=WARN | trans=1431942292-379-0000000011 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[177] : Bad configuration (Building collectionName=fiwareServicePath + '_' + destination (sth_test_1234567890123_456789012345678901234567890123456789012345678) and its length is greater than 64)
```

Feature: mongo_raw.feature
Scenario: 
```    
      received a notification at Cygnus and store it as raw data with several entities types and entities id (resource tag)
```
Datasets: 
```
     | with max length allowed | json    |
     | with max length allowed | xml     |
```

**Comment by iariasleon** [comment]
Probably, the lengths will be per sinks (still to be defined)

**Comment by frbattid** [comment]
+1 to your last comment.

**Comment by frbattid** [comment]
Thinking about this, I've realized it makes no sense to control the length of the collections and/or databases. It makes no sense because apart from tracing it in logs, nothing can be done (truncation is not an option since collisions may appear and Cygnus cannot assume any decission regarding storage elements). By the way, such logs will be traced as well once the database and/or collection creation is executed.

Of course, this apply to all the sinks, where similar checks are performed.

My proposal is to remove those checks from the code.

Copying @gtorodelvalle , it is always interesting his poing of view.

**Comment by gtorodelvalle** [comment]
Hey! Yeah, I do agree... :) There are more complex techniques such as using hashing for the naming (as it is currently implemented in the STH case) but I am not aware of anyone using it, so probably the complexity added by these techniques are not worth the effort... In my opinion the right path is to return an error to the Context Broker whenever Cygnus is not able to persist the data. If we find this approach being too limited, we can always consider possible solutions such as hashing as previously mentioned.

**Comment by gtorodelvalle** [comment]
It seems in English is something like: "Don't cry before you're hurt"... :)

**Comment by frbattid** [comment]
Finally, this issue will go on the original direction: there will be an active check, and the size limitations will be in a per sink fashion.

**Comment by frbattid** [comment]
When implementing this issue, multivalued FIWARE service path headers must be taken into account (the size limitation must be applied to each individual value).

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1137
