### ISSUE TITLE
removed feature matching_table 

### ISSUE THREAD

**Issue by c-castillo** [telefonicaid/fiware-cygnus#496]
Hi,

I have a old cygnus setup with matching_table rule enabled. Now, I have to replicate this setup in another server (new version of cygnus doesn't include matching_table). How can I replicate the same behaviour in the new version of cygnus?

**Comment by frbattid** [comment]
Hi,

It is a matter of naming and format, but the feature is there. From Cygnus version 0.8.1, the:

    cygnusagent.sources.http-source.interceptors.de.matching_table = /usr/cygnus/conf/matching_table.conf

paramter as replaced by:

    cygnusagent.sources.http-source.interceptors.gi.grouping_rules_conf_file = /usr/cygnus/conf/grouping_rules.conf

Regarding the format, now it is written in JSON instead of a CSV. You have all details [here](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/design/interceptors.md#section3); I think it will be easy for you to move from CSV to JSON since the format is very straightforard. Anyway, let me know if you have any problem.

**Comment by frbattid** [comment]
Any update, @c-castillo?

**Comment by frbattid** [comment]
Closing since no updates were received from the user.

**Comment by c-castillo** [comment]
Oh sorry, the answer was correct

**Comment by frbattid** [comment]
Great to hear that :)
