### ISSUE TITLE
[all sinks] All sinks must stop when using an unsupported data_model

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#718]
While issues #686, #687, #688, #689, #690, #691 and #720 are implemented, the related sinks must stop when using an unsupported `data_model`. The check must be done at the `configure` method.

The implementation of this issue will not have an entry in `CHANGES_NEXT_RELEASE` since this is a continuation of the issue https://github.com/telefonicaid/fiware-cygnus/issues/659 and will implemented in the same sprint. Thus, once merged the corresponding PR, it must be linked both here and https://github.com/telefonicaid/fiware-cygnus/issues/659.

<b>Effort: 1 man day</b>

**Comment by frbattid** [comment]
In the particular case of OrionMongoSink, the combination `data_model=dm-by-attribute` + `attr_persistence=column` must be avoided as well, despite each one of them are valid single configurations.

**Comment by pcoello25** [comment]
Fix is neccesary because if we get and unsupported `data_model` in our sink we only have to stop it, not cygnus (we can have more than a sink running and stop cygnus would be an error).

As @frbattid said, the change will be in the `configure` method, where we'll print an error trace and stop the sink properly in the moment we receive and bad `data_model`.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/783
