### ISSUE TITLE
No enum constant com.telefonica.iot.cygnus.sinks.OrionSink.DataModel.COLLECTIONPERSERVICEPATH

### ISSUE THREAD

**Issue by web-bert** [telefonicaid/fiware-cygnus#816]
Hi,

I have been using Cygnus 0.10.0 on a VM but now I'm trying to use Docker to setup my system. I have realised that the latest version is 0.12.1 and when trying to start cygnus with my 0.10.0 config, I see the following error:

```bash
java.lang.IllegalArgumentException: No enum constant com.telefonica.iot.cygnus.sinks.OrionSink.DataModel.COLLECTIONPERSERVICEPATH
cygnus_1           | 	at java.lang.Enum.valueOf(Enum.java:236)
cygnus_1           | 	at com.telefonica.iot.cygnus.sinks.OrionSink$DataModel.valueOf(OrionSink.java:77)
cygnus_1           | 	at com.telefonica.iot.cygnus.sinks.OrionSink.configure(OrionSink.java:120)
cygnus_1           | 	at com.telefonica.iot.cygnus.sinks.OrionMongoBaseSink.configure(OrionMongoBaseSink.java:128)
cygnus_1           | 	at org.apache.flume.conf.Configurables.configure(Configurables.java:41)
cygnus_1           | 	at org.apache.flume.node.AbstractConfigurationProvider.loadSinks(AbstractConfigurationProvider.java:418)
cygnus_1           | 	at org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(AbstractConfigurationProvider.java:103)
cygnus_1           | 	at org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:140)
cygnus_1           | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
cygnus_1           | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
cygnus_1           | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
cygnus_1           | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
cygnus_1           | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
cygnus_1           | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
cygnus_1           | 	at java.lang.Thread.run(Thread.java:745)
```

Has something changed? Is [my config](https://gist.github.com/web-bert/9de831485ef5437228ce) still valid?

I noticed that these lines were added:

```java
# number of notifications to be included within a processing batch
cygnusagent.sinks.mongo-sink.batch_size = 100
# timeout for batch accumulation
cygunsagent.sinks.mongo-sink.batch_timeout = 30
```

So I added these to my 0.10.0 config

**Comment by frbattid** [comment]
The `data_model` parameter, already available for `OrionMongoSink` and `OrionSTHSink`, has been made general for all the sinks. [This](https://github.com/telefonicaid/fiware-cygnus/issues/659) is the issue describing it, and [this](https://github.com/telefonicaid/fiware-cygnus/issues/684) the PR implementing it.

With such a generalization, now the possbile values for `data_model` are:

* `dm-by-service` --> not supported by `OrionMongoSink` nor `OrionSTHSink`
* `dm-by-service-path` --> replaces `collection-by-service-parh`
* `dm-by-entity` --> replaces `collection-by-entityand`
* `dm-by-attribute` --> replaces `collection-by-attribute`

The problem is release 0.12.1 has a wrong preconfigured value by default (the one the error trace is saying). The fix is quite simple: just configure the `data_model` parameter with the right default value, i.e. `dm-by-entity`.

Let me know if this works.

**Comment by web-bert** [comment]
Yes that works, thank you. I have created [a pull request](https://github.com/telefonicaid/fiware-cygnus/pull/817) to update the conf
